// Code generated by hertz generator.

package video

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideostreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpopularvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
