services:
  # Redis 服务，用于缓存、会话管理等，提供键值存储功能
  tiktok-redis:
    container_name: tiktok-redis
    image: redis:bookworm
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    networks:
      - tiktok

  # MySQL 服务，提供关系型数据库，用于存储结构化数据
  tiktok-mysql:
    container_name: tiktok-mysql
    image: mysql:9.0.1
    env_file:
      - "./env/mysql.env"
    ports:
      - "3306:3306"
    networks:
      - tiktok
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  # etcd 服务，分布式键值存储系统，用于服务发现、配置管理
  tiktok-etcd:
    container_name: tiktok-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
      - ./data/etcd:/etcd-data
    networks:
      - tiktok
    entrypoint: [ "sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd" ]

  # Kafka 服务，分布式流处理平台，用于构建实时数据管道和流应用
  kafka:
    container_name: tiktok-kafka
    image: bitnami/kafka:latest
    restart: always
    user: root
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - ./env/kafka.env
    volumes:
      - ./data/kafka:/bitnami/kafka
    networks:
      - tiktok

  # Kafka UI 服务，为 Kafka 提供可视化管理和监控界面
  kafka-ui:
    container_name: tiktok-kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "9091:8080"
    env_file:
      - ./env/kafka-ui.env
    networks:
      - tiktok

  # RocketMQ NameServer 服务，负责管理 Broker 的元数据
  rmqnamesrv:
    image: apache/rocketmq:4.9.6
    container_name: tiktok-rmqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - ./data/rocketmq/namesrv/logs:/opt/logs
      - ./data/rocketmq/namesrv/store:/opt/store
    command: sh mqnamesrv
    networks:
      tiktok:
        aliases:
          - rmqnamesrv
    mem_limit: 250m

  # RocketMQ Broker 服务，负责消息的存储、转发等核心功能
  rmqbroker:
    image: apache/rocketmq:4.9.6
    container_name: tiktok-rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ./data/rocketmq/broker/logs:/opt/logs
      - ./data/rocketmq/broker/store:/opt/store
      - ../config/rocketmq/broker.conf:/home/rocketmq/broker.conf
      - ../config/rocketmq/plain_acl.yml:/home/rocketmq/rocketmq-4.9.6/conf/plain_acl.yml
    env_file:
      - ./env/rocket-broker.env
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.6/conf/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      tiktok:
        aliases:
          - rmqbroker
    mem_limit: 750m

  # OpenTelemetry 收集器，收集、处理和导出可观测性数据（指标、追踪等）
  tiktok-otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    container_name: tiktok-otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}" ]
    volumes:
      - ../config/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679" # zpages extension
    depends_on:
      - tiktok-jaeger
    networks:
      - tiktok

  # Jaeger 服务，分布式追踪系统，用于监控和排查微服务性能问题
  tiktok-jaeger:
    container_name: tiktok-jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "6831:6831"
      - "4317"
    networks:
      - tiktok

networks:
  tiktok:
    driver: bridge
    name: tiktok
