mysql:
  addr: 127.0.0.1:3306
  database: TikTok
  username: TikTok
  password: root
  charset: utf8mb4

oss:
  bucket: ""
  accessKey: ""
  secretKey:  ""
  domain: ""

kafka:
  address: 127.0.0.1:9092
  network: tcp
  user: tiktok
  password: tiktok-password

redis:
  addr: 127.0.0.1:6379
  username: "TikTok"
  password: "TikTok"

etcd:
  addr: 127.0.0.1:2379

pprof:
  addr: :6060

services:
  gateway:
    name : gateway
    load-balance: true
    addr:
      - 127.0.0.1:10001
      - 127.0.0.1:10000
  user:
    name: user
    load-balance: false
    addr:
      - 127.0.0.1:10002
  video:
    name: video
    load-balance: false
    addr:
      - 127.0.0.1:10003
  interact:
    name : interact
    load-balance: false
    addr:
      - 127.0.0.1:10004
  socialize:
    name : socialize
    load-balance: false
    addr:
      - 127.0.0.1:10005
  websocket:
    name : websocket
    load-balance: false
    addr:
      - 127.0.0.1:10006