// Code generated by hertz generator.

package interact

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _like0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querylikelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
